platform :ios, '13.0'

target 'ToDoo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Toast-Swift', '~> 5.0.0'
  pod 'SwipeCellKit'
  pod 'JTAppleCalendar', '7.1.7'

  target 'ToDooTests'
  target 'ToDooUITests'
end